CREATE DATABASE customer_behavior;
USE customer_behavior;
SHOW tables;
SELECT * 
FROM customer_shopping_behavior;
DESCRIBE customer_shopping_behavior;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT 
    Gender,
    SUM(purchase_amount_usd) AS total_revenue
FROM customer_shopping_behavior
GROUP BY Gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
-- Approach: compute overall avg, then find customers whose avg spending on discounted purchases is > overall avg.
SELECT
  `Customer ID`,
  COUNT(*) AS discounted_txn_count,
  ROUND(AVG(purchase_amount_usd),2) AS avg_spend_on_discounted,
  ROUND(SUM(purchase_amount_usd),2) AS total_spend_on_discounted
FROM customer_shopping_behavior
WHERE `Discount Applied` IS NOT NULL
  AND `Discount Applied` <> 'No'
GROUP BY `Customer ID`
HAVING AVG(purchase_amount_usd) > (SELECT AVG(purchase_amount_usd) FROM customer_shopping_behavior)
ORDER BY avg_spend_on_discounted DESC;

-- Q3. Which are the top 5 products with the highest average review rating?
-- Approach: average rating per item, show top 5 (ties broken by count of reviews)
SELECT
  `Item Purchased`,
  ROUND(AVG(`Review Rating`),2) AS avg_rating,
  COUNT(*) AS num_reviews
FROM customer_shopping_behavior
WHERE `Review Rating` IS NOT NULL
GROUP BY `Item Purchased`
ORDER BY avg_rating DESC, num_reviews DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
-- Approach: compute avg and count for the two shipping types
SELECT
  `Shipping Type`,
  COUNT(*) AS transactions,
  ROUND(AVG(purchase_amount_usd),2) AS avg_purchase,
  ROUND(SUM(purchase_amount_usd),2) AS total_revenue
FROM customer_shopping_behavior
WHERE `Shipping Type` IN ('Standard','Express')
GROUP BY `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- Approach: group by Subscription Status (e.g., 'Yes' / 'No') and show count, avg, total
SELECT
  `Subscription Status`,
  COUNT(*) AS transactions,
  ROUND(AVG(purchase_amount_usd),2) AS avg_purchase,
  ROUND(SUM(purchase_amount_usd),2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- Approach: for each product compute percent_discounted = discounted_count / total_count * 100
SELECT
  `Item Purchased`,
  COUNT(*) AS total_purchases,
  SUM(`Discount Applied` <> 'No') AS discounted_purchases,
  ROUND(100 * SUM(`Discount Applied` <> 'No') / COUNT(*), 2) AS pct_discounted
FROM customer_shopping_behavior
GROUP BY `Item Purchased`
HAVING total_purchases >= 5   -- optional: ignore extremely rare items
ORDER BY pct_discounted DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- Rules used: New = 0 previous purchases, Returning = 1-4, Loyal = 5 or more
-- Show number of customers, avg spend per customer (total), and total revenue per segment
SELECT
  segment,
  COUNT(*) AS customers,
  ROUND(AVG(total_spend),2) AS avg_total_spend_per_customer,
  ROUND(SUM(total_spend),2) AS segment_total_revenue
FROM (
  -- compute total spend per customer then map to segment
  SELECT
    `Customer ID`,
    CASE
      WHEN COALESCE(`Previous Purchases`,0) = 0 THEN 'New'
      WHEN COALESCE(`Previous Purchases`,0) BETWEEN 1 AND 4 THEN 'Returning'
      ELSE 'Loyal'
    END AS segment,
    SUM(purchase_amount_usd) AS total_spend
  FROM customer_shopping_behavior
  GROUP BY `Customer ID`, CASE
      WHEN COALESCE(`Previous Purchases`,0) = 0 THEN 'New'
      WHEN COALESCE(`Previous Purchases`,0) BETWEEN 1 AND 4 THEN 'Returning'
      ELSE 'Loyal'
    END
) AS per_customer
GROUP BY segment
ORDER BY FIELD(segment, 'Loyal', 'Returning', 'New');

-- Q8. What are the top 3 most purchased products within each category? 
-- Approach: count purchases per (category, item), use ROW_NUMBER() to rank then keep top 3 per category (MySQL 8+)
WITH item_counts AS (
  SELECT
    Category,
    `Item Purchased` AS item,
    COUNT(*) AS purchases,
    ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(*) DESC) AS rn
  FROM customer_shopping_behavior
  GROUP BY Category, `Item Purchased`
)
SELECT Category, item, purchases
FROM item_counts
WHERE rn <= 3
ORDER BY Category, purchases DESC;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Approach: compute subscription rate for repeat buyers (>5 previous purchases) vs others, with counts and percent_subscribed
SELECT
  stage,
  COUNT(*) AS customers,
  SUM(is_subscribed) AS subscribed_count,
  ROUND(100 * SUM(is_subscribed) / COUNT(*), 2) AS pct_subscribed
FROM (
  SELECT
    `Customer ID`,
    CASE 
      WHEN MAX(COALESCE(`Previous Purchases`,0)) > 5 
      THEN 'Repeat (>5)' 
      ELSE 'Others (<=5)' 
    END AS stage,
    MAX(CASE 
          WHEN `Subscription Status` = 'Yes' THEN 1 
          ELSE 0 
        END) AS is_subscribed
  FROM customer_shopping_behavior
  GROUP BY `Customer ID`
) AS customer_summary
GROUP BY stage;

-- Q10. What is the revenue contribution of each age group? 
SELECT
  CASE
    WHEN Age < 25 THEN '<25'
    WHEN Age BETWEEN 25 AND 34 THEN '25-34'
    WHEN Age BETWEEN 35 AND 44 THEN '35-44'
    WHEN Age BETWEEN 45 AND 54 THEN '45-54'
    ELSE '55+'
  END AS age_group,
  ROUND(SUM(purchase_amount_usd),2) AS total_revenue,
  ROUND(100 * SUM(purchase_amount_usd) / (SELECT SUM(purchase_amount_usd) FROM customer_shopping_behavior), 2) AS pct_of_total
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY pct_of_total DESC;

